version: '3.8'
services:
  app:
    image: localhost:5001/webapp:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 3 
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: mydatabase
    volumes:
      - ./webapp:/app
      - /app/node_modules

  db:
    image: localhost:5001/mydatabase:latest
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    deploy:
      replicas: 1
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/mysql-init:/docker-entrypoint-initdb.d

volumes:
  db-data:

networks:
  default:
    name: app-network
