# Utilisation de l'image officielle Node.js version 16 sur Alpine Linux comme base
FROM node:16-alpine

# Définition du répertoire de travail dans le conteneur
WORKDIR /app

# Copie des fichiers package.json et package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installation des dépendances Node.js
RUN npm install

# Copie du reste des fichiers du projet dans le répertoire de travail du conteneur
COPY . .

# Exposition du port 3000 pour permettre aux applications externes de se connecter à l'application
EXPOSE 3000

# Commande de démarrage de l'application
CMD ["node", "index.js"]
